// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

#[allow(unused_imports)]
use crate::auto::*;

#[doc(alias = "GimpBablFormat")]
pub type BablFormat = babl::Object;
#[doc(alias = "GimpColorArray")]
pub type ColorArray = gegl::Color;
#[doc(alias = "GimpCoreObjectArray")]
pub type CoreObjectArray = glib::Object;
