// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi};

glib::wrapper! {
    /// The base class for [class`DrawableFilter`] specific config objects.
    ///
    /// A drawable filter config is created by a [class`DrawableFilter`] using
    /// [method`DrawableFilter`] and its properties match the
    /// filter's arguments in number, order and type.
    ///
    /// This is an Abstract Base Class, you cannot instantiate it.
    ///
    /// # Implements
    ///
    /// [`trait@glib::ObjectExt`]
    #[doc(alias = "GimpDrawableFilterConfig")]
    pub struct DrawableFilterConfig(Object<ffi::GimpDrawableFilterConfig, ffi::GimpDrawableFilterConfigClass>);

    match fn {
        type_ => || ffi::gimp_drawable_filter_config_get_type(),
    }
}

impl DrawableFilterConfig {
        pub const NONE: Option<&'static DrawableFilterConfig> = None;
    
}
