// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::{ffi,Procedure};

glib::wrapper! {
    #[doc(alias = "GimpImageProcedure")]
    pub struct ImageProcedure(Object<ffi::GimpImageProcedure, ffi::GimpImageProcedureClass>) @extends Procedure;

    match fn {
        type_ => || ffi::gimp_image_procedure_get_type(),
    }
}

impl ImageProcedure {}
