[options]
library = "Gimp"
version = "3.0"
min_cfg_version = "3.0"
target_path = "."
girs_directories = ["../../gir-files/", "../../"]
work_mode = "sys"
single_version_file = true

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
    "Babl",
    "GdkPixbuf",
    "Gegl",
    "cairo",
    "Pango",
]

# propably needs fixing with either a manual impl or in the Gimp-3.0.gir file
ignore = [
    "Gimp.MAX_MEMSIZE",
    "Gimp.CpuAccelFlags",
]
