[options]
library = "Gimp"
version = "3.0"
min_cfg_version = "3.0"
target_path = "."
girs_directories = ["../gir-files/", "../"]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
	"Gimp.ImageBaseType",
	"Gimp.Precision",
	"Gimp.ColorProfile",
	"Gimp.ColorRenderingIntent",
	"Gimp.ConvertDitherType",
	"Gimp.ConvertPaletteType",
	"Gimp.Channel",
	"Gimp.Path",
	"Gimp.Metadata",
	"Gimp.MetadataSaveFlags",
	"Gimp.Item",
	"Gimp.Drawable",
	"Gimp.ChannelOps",
	"Gimp.ChannelType",
	"Gimp.OrientationType",
	"Gimp.LayerMode",
	"Gimp.Selection",
	"Gimp.PixbufTransparency",
	"Gimp.Unit",
	"Gimp.GridStyle",
	"Gimp.MergeType",
	"Gimp.RotationType",
	"Gimp.PDBErrorHandler",
	"Gimp.PDBProcType",
	"Gimp.ProcedureConfig",
	"Gimp.Brush",
	"Gimp.Font",
	"Gimp.Gradient",
	"Gimp.Pattern",
	"Gimp.Resource",
	"Gimp.IconType",
	"Gimp.PDBStatusType",
	"Gimp.ArgumentSync",
	"Gimp.ProcedureSensitivityMask",
	"Gimp.RunMode",
	"Gimp.AddMaskType",
	"Gimp.LayerMask",
    "Gimp.ColorArray",
    "Gimp.CoreObjectArray",
    "Gimp.Array",
    "Gimp.BablFormat",
    "Gimp.ImageType",
    "Gimp.PathStrokeType",
    "Gimp.DrawableFilter",
    "Gimp.GradientSegmentType",
    "Gimp.BrushGeneratedShape",
    "Gimp.GradientSegmentColor",
    "Gimp.DrawableFilterConfig",
    "Gimp.TransferMode",
    "Gimp.HistogramChannel",
    "Gimp.MetadataColorspace",
    "Gimp.DesaturateMode",
    "Gimp.FillType",
    "Gimp.GradientType",
    "Gimp.ForegroundExtractMode",
    "Gimp.ColorTag",
    "Gimp.HueRange",
    "Gimp.LayerColorSpace",
    "Gimp.LayerCompositeMode",
    "Gimp.CheckSize",
    "Gimp.MaskApplyMode",
    "Gimp.CheckType",
    "Gimp.OffsetType",
    "Gimp.CloneType",
    "Gimp.GradientBlendColorSpace",
    "Gimp.RepeatMode",
    "Gimp.InkBlobType",
    "Gimp.InterpolationType",
    "Gimp.CapStyle",
    "Gimp.JoinStyle",
    "Gimp.SelectCriterion",
    "Gimp.StrokeMethod",
    "Gimp.TransformDirection",
    "Gimp.TransformResize",
    "Gimp.ConvolveType",
    "Gimp.Display",
    "Gimp.DodgeBurnType",
    "Gimp.BrushApplicationMode",
    "Gimp.PaintApplicationMode",
    "Gimp.ExportOptions",
    "Gimp.ExportCapabilities",
    "Gimp.ColorConfig",
    "Gimp.PDB",
    "Gimp.ColorManagementMode",
    "Gimp.MessageHandlerType",
    "Gimp.ColorManaged",
    "Gimp.ColorTransform",
    "Gimp.ColorTransformFlags",
    "Gimp.ComponentType",
    "Gimp.ConfigError",
    "Gimp.ConfigPathType",
    "Gimp.ExportReturn",
    "Gimp.Matrix2",
    "Gimp.Matrix3",
    "Gimp.RenderFunc",
    "Gimp.PutPixelFunc",
    "Gimp.ProgressFunc",
    "Gimp.FileChooserAction",
    "Gimp.RunImageFunc",
    "Gimp.RunFunc",
    "Gimp.FileProcedure",
    "Gimp.GroupLayer",
    "Gimp.LoadProcedure",
    "Gimp.MetadataLoadFlags",
    "Gimp.Module",
    "Gimp.ModuleState",
    "Gimp.ModuleDB",
    "Gimp.ModuleError",
    "Gimp.RunLoadFunc",
    "Gimp.ProgressCommand",
    "Gimp.SizeType",
    "Gimp.StackTraceMode",
    "Gimp.TextDirection",
    "Gimp.TextHintStyle",
    "Gimp.TextLayer",
    "Gimp.TextJustification",
    "Gimp.ThumbnailProcedure",
    "Gimp.UnitID",
    "Gimp.VectorLoadProcedure",
    "Gimp.RunThumbnailFunc",
    "Gimp.ExtractVectorFunc",
    "Gimp.RunVectorLoadFunc",

#    "Gimp.BatchProcedure",
#    "Gimp.ConfigPath",
#    "Gimp.Config",
#    "Gimp.CpuAccelFlags",
#    "Gimp.EnumDesc",
#    "Gimp.ExportProcedure",
#    "Gimp.VectorLoadData",
#    "Gimp.FlagsDesc",
#    "Gimp.Matrix4",
#    "Gimp.Memsize",
#    "Gimp.PixPipeParams",
#    "Gimp.ProgressVtable",
#    "Gimp.ModuleInfo",
#    "Gimp.Scanner",
#    "Gimp.Vector4",
#    "Gimp.ConfigInterface",
]

manual = [
    "Babl.Object",
    "cairo.Context",
    "cairo.Surface",
    "cairo.Pattern",
    "Pango.FontDescription",
	"Gio.File",
    "Gio.OutputStream",
    "Gio.ListModel",
    "GLib.String",
	"GLib.Bytes",
	"GLib.Error",
	"GLib.Quark",
	"GLib.IOChannel",
    "GLib.TokenType",
    "GLib.Scanner",
    "GLib.DestroyNotify",
    "GLib.DateTime",
    "GObject.FlagsValue",
    "GObject.EnumValue",
    "GObject.Object",
    "GObject.Value",
	"GObject.ParamFlags",
	"GObject.ParamSpec",
    "GObject.ParamSpecBoxed",
    "GObject.ParamSpecObject",
    "GObject.ParamSpecString",
    "GObject.ParamSpecUInt64",
    "Gegl.Rectangle",
	"Gegl.Color",
	"Gegl.Buffer",
    "Gegl.DistanceMetric",
	"GdkPixbuf.Pixbuf",

    # TODO check impl and add methods
    "Gimp.Vector2",
    "Gimp.Vector3",

#    "GObject.FlagsClass",
#    "GObject.EnumClass",
#    "GObject.TypeModule",
#    "GObject.TypePlugin",
]

[[object]]
name = "Gimp.ConfigWriter"
status = "generate"
    [[object.function]]
    name = "new_from_string"
    ignore = true

[[object]]
name = "Gimp.Palette"
status = "generate"
    [[object.function]]
    name = "set_colormap"
    ignore = true

[[object]]
name = "Gimp.Procedure"
status = "generate"
manual_traits = ["ProcedureExtManual"]
    [[object.function]]
    name = "set_sensitivity_mask"
    ignore = true

[[object]]
name = "Gimp.ImageProcedure"
status = "generate"
manual_traits = ["ImageProcedureExtManual"]
    [[object.function]]
    name = "new"
    ignore = true

[[object]]
name = "Gimp.Parasite"
status = "generate"
    [[object.function]]
    name = "compare"
    ignore = true

[[object]]
name = "Gimp.Choice"
status = "generate"
    [[object.function]]
    name = "get_documentation"
    ignore = true

[[object]]
name = "Gimp.Image"
status = "generate"
    [[object.function]]
    name = "metadata_save_prepare"
    ignore = true
    [[object.function]]
    name = "pick_color"
    ignore = true
    [[object.function]]
    name = "set_selected_channels"
    ignore = true
    [[object.function]]
    name = "set_selected_layers"
    ignore = true
    [[object.function]]
    name = "set_selected_paths"
    ignore = true

[[object]]
name = "Gimp.*"
status = "generate"
    [[object.function]]
    name = "color_list_names"
    ignore = true
    [[object.function]]
    name = "color_parse_css_substring"
    ignore = true
    [[object.function]]
    name = "color_parse_hex_substring"
    ignore = true
    [[object.function]]
    name = "color_parse_name_substring"
    ignore = true
    [[object.function]]
    name = "edit_copy"
    ignore = true
    [[object.function]]
    name = "edit_cut"
    ignore = true
    [[object.function]]
    name = "edit_named_copy"
    ignore = true
    [[object.function]]
    name = "edit_named_cut"
    ignore = true
    [[object.function]]
    name = "enum_get_value"
    ignore = true
    [[object.function]]
    name = "flags_get_first_value"
    ignore = true
    [[object.function]]
    name = "color_array_copy"
    ignore = true
    [[object.function]]
    name = "color_array_free"
    ignore = true
    [[object.function]]
    name = "color_array_get_length"
    ignore = true
    [[object.function]]
    name = "core_object_array_get_length"
    ignore = true
    [[object.function]]
    name = "cairo_surface_create_buffer"
    ignore = true
    [[object.function]]
    name = "cairo_surface_get_format"
    ignore = true
    [[object.function]]
    name = "color_is_out_of_gamut"
    ignore = true
    [[object.function]]
    name = "pixbuf_get_format"
    ignore = true
    [[object.function]]
    name = "cairo_checkerboard_create"
    ignore = true
    [[object.function]]
    name = "vector_2d_to_3d_val"
    ignore = true

[[object]]
name = "Gimp.PlugIn"
status = "generate"
    [[object.property]]
    name = "read-channel"
    ignore = true
    [[object.property]]
    name = "write-channel"
    ignore = true

[[object]]
name = "Gimp.ValueArray"
status = "generate"
    [[object.function]]
    name = "new_from_values"
    ignore = true

[[object]]
name = "Gimp.Layer"
status = "generate"
    [[object.function]]
    name = "new_from_surface"
    ignore = true

[[object]]
name = "Gimp.ParamArray"
status = "ignore"

[[object]]
name = "Gimp.ParamResource"
status = "ignore"

[[object]]
name = "Gimp.ParamBrush"
status = "ignore"

[[object]]
name = "Gimp.ParamDrawable"
status = "ignore"

[[object]]
name = "Gimp.ParamChannel"
status = "ignore"

[[object]]
name = "Gimp.ParamChoice"
status = "ignore"

[[object]]
name = "Gimp.ParamObject"
status = "ignore"

[[object]]
name = "Gimp.ParamColor"
status = "ignore"

[[object]]
name = "Gimp.ParamConfigPath"
status = "ignore"

[[object]]
name = "Gimp.ParamCoreObjectArray"
status = "ignore"

[[object]]
name = "Gimp.ParamDisplay"
status = "ignore"

[[object]]
name = "Gimp.ParamDoubleArray"
status = "ignore"

[[object]]
name = "Gimp.ParamItem"
status = "ignore"

[[object]]
name = "Gimp.ParamDrawableFilter"
status = "ignore"

[[object]]
name = "Gimp.ParamExportOptions"
status = "ignore"

[[object]]
name = "Gimp.ParamFile"
status = "ignore"

[[object]]
name = "Gimp.ParamFont"
status = "ignore"

[[object]]
name = "Gimp.ParamGradient"
status = "ignore"

[[object]]
name = "Gimp.ParamLayer"
status = "ignore"

[[object]]
name = "Gimp.ParamGroupLayer"
status = "ignore"

[[object]]
name = "Gimp.ParamImage"
status = "ignore"

[[object]]
name = "Gimp.ParamInt32Array"
status = "ignore"

[[object]]
name = "Gimp.ParamLayerMask"
status = "ignore"

[[object]]
name = "Gimp.ParamMatrix2"
status = "ignore"

[[object]]
name = "Gimp.ParamMatrix3"
status = "ignore"

[[object]]
name = "Gimp.ParamMemsize"
status = "ignore"

[[object]]
name = "Gimp.ParamPalette"
status = "ignore"

[[object]]
name = "Gimp.ParamParasite"
status = "ignore"

[[object]]
name = "Gimp.ParamPath"
status = "ignore"

[[object]]
name = "Gimp.ParamPattern"
status = "ignore"

[[object]]
name = "Gimp.ParamSelection"
status = "ignore"

[[object]]
name = "Gimp.ParamSpecChoice"
status = "ignore"

[[object]]
name = "Gimp.ParamSpecColor"
status = "ignore"

[[object]]
name = "Gimp.ParamSpecCoreObjectArray"
status = "ignore"

[[object]]
name = "Gimp.ParamSpecDisplay"
status = "ignore"

[[object]]
name = "Gimp.ParamSpecDrawableFilter"
status = "ignore"

[[object]]
name = "Gimp.ParamSpecObject"
status = "ignore"

[[object]]
name = "Gimp.ParamSpecFile"
status = "ignore"

[[object]]
name = "Gimp.ParamSpecImage"
status = "ignore"

[[object]]
name = "Gimp.ParamSpecItem"
status = "ignore"

[[object]]
name = "Gimp.ParamSpecResource"
status = "ignore"

[[object]]
name = "Gimp.ParamSpecUnit"
status = "ignore"

[[object]]
name = "Gimp.ParamSpecValueArray"
status = "ignore"

[[object]]
name = "Gimp.ParamTextLayer"
status = "ignore"

[[object]]
name = "Gimp.ParamUnit"
status = "ignore"

[[object]]
name = "Gimp.ParamValueArray"
status = "ignore"
