[options]
library = "Gimp"
version = "3.0"
min_cfg_version = "3.0"
target_path = "."
girs_directories = ["../gir-files/", "../"]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
	"Gimp.ImageBaseType",
	"Gimp.Precision",
	"Gimp.ColorProfile",
	"Gimp.ColorRenderingIntent",
	"Gimp.ConvertDitherType",
	"Gimp.ConvertPaletteType",
	"Gimp.Channel",
	"Gimp.Path",
	"Gimp.Metadata",
	"Gimp.MetadataSaveFlags",
	"Gimp.Item",
	"Gimp.Drawable",
	"Gimp.ChannelOps",
	"Gimp.ChannelType",
	"Gimp.OrientationType",
	"Gimp.LayerMode",
	"Gimp.Selection",
	"Gimp.PixbufTransparency",
	"Gimp.Unit",
	"Gimp.GridStyle",
	"Gimp.MergeType",
	"Gimp.RotationType",
	"Gimp.PDBErrorHandler",
	"Gimp.PDBProcType",
	"Gimp.ProcedureConfig",
	"Gimp.Brush",
	"Gimp.Font",
	"Gimp.Gradient",
	"Gimp.Pattern",
	"Gimp.Resource",
	"Gimp.IconType",
	"Gimp.PDBStatusType",
	"Gimp.ArgumentSync",
	"Gimp.ProcedureSensitivityMask",
	"Gimp.RunMode",
	"Gimp.AddMaskType",
	"Gimp.LayerMask",
    "Gimp.ColorArray",
    "Gimp.CoreObjectArray",
    "Gimp.Array",
    "Gimp.BablFormat",
    "Gimp.ImageType",
    "Gimp.PathStrokeType",
    "Gimp.DrawableFilter",
    "Gimp.GradientSegmentType",
    "Gimp.BrushGeneratedShape",
    "Gimp.GradientSegmentColor",
    "Gimp.DrawableFilterConfig",
    "Gimp.TransferMode",
    "Gimp.HistogramChannel",
    "Gimp.MetadataColorspace",
    "Gimp.DesaturateMode",
    "Gimp.FillType",
    "Gimp.GradientType",
    "Gimp.ForegroundExtractMode",
    "Gimp.ColorTag",
    "Gimp.HueRange",
    "Gimp.LayerColorSpace",
    "Gimp.LayerCompositeMode",
    "Gimp.CheckSize",
    "Gimp.MaskApplyMode",
    "Gimp.CheckType",
    "Gimp.OffsetType",
    "Gimp.CloneType",
    "Gimp.GradientBlendColorSpace",
    "Gimp.RepeatMode",
    "Gimp.InkBlobType",
    "Gimp.InterpolationType",
    "Gimp.CapStyle",
    "Gimp.JoinStyle",
    "Gimp.SelectCriterion",
    "Gimp.StrokeMethod",
    "Gimp.TransformDirection",
    "Gimp.TransformResize",
    "Gimp.ConvolveType",
    "Gimp.Display",
    "Gimp.DodgeBurnType",
    "Gimp.BrushApplicationMode",
    "Gimp.PaintApplicationMode",
    "Gimp.ExportOptions",
    "Gimp.ExportCapabilities",
    "Gimp.ColorConfig",
    "Gimp.PDB",
    "Gimp.ColorManagementMode",
    "Gimp.MessageHandlerType",
    "Gimp.ColorManaged",
    "Gimp.ColorTransform",
    "Gimp.ColorTransformFlags",
    "Gimp.ComponentType",
    "Gimp.ConfigError",
    "Gimp.ConfigPathType",
    "Gimp.ExportReturn",
    "Gimp.Matrix2",
#    "Gimp.ConfigPath",
#    "Gimp.Config",
#    "Gimp.CpuAccelFlags",
#    "Gimp.EnumDesc",
#    "Gimp.FlagsDesc",
#    "Gimp.Vector3",
#    "Gimp.Matrix3",
#    "Gimp.PixPipeParams",
#    "Gimp.CpuAccelFlags",
]

manual = [
    "Babl.Object",
    "cairo.Context",
    "cairo.Surface",
    "cairo.Pattern",
    "Pango.FontDescription",
	"Gio.File",
    "Gio.OutputStream",
    "GLib.String",
	"GLib.Bytes",
	"GLib.Error",
	"GLib.Quark",
	"GLib.IOChannel",
    "GObject.FlagsValue",
    "GObject.EnumValue",
    "GObject.Object",
    "GObject.Value",
	"GObject.ParamFlags",
	"GObject.ParamSpec",
    "Gegl.Rectangle",
	"Gegl.Color",
	"Gegl.Buffer",
    "Gegl.DistanceMetric",
	"GdkPixbuf.Pixbuf",
#    "GObject.FlagsClass",
#    "GObject.EnumClass",
]

[[object]]
name = "Gimp.ConfigWriter"
status = "generate"
    [[object.function]]
    name = "new_from_string"
    ignore = true

[[object]]
name = "Gimp.Palette"
status = "generate"
    [[object.function]]
    name = "set_colormap"
    ignore = true

[[object]]
name = "Gimp.Procedure"
status = "generate"
manual_traits = ["ProcedureExtManual"]
    [[object.function]]
    name = "set_sensitivity_mask"
    ignore = true

[[object]]
name = "Gimp.ImageProcedure"
status = "generate"
manual_traits = ["ImageProcedureExtManual"]
    [[object.function]]
    name = "new"
    ignore = true

[[object]]
name = "Gimp.Parasite"
status = "generate"
    [[object.function]]
    name = "compare"
    ignore = true

[[object]]
name = "Gimp.Choice"
status = "generate"
    [[object.function]]
    name = "get_documentation"
    ignore = true

[[object]]
name = "Gimp.Image"
status = "generate"
    [[object.function]]
    name = "metadata_save_prepare"
    ignore = true
    [[object.function]]
    name = "pick_color"
    ignore = true
    [[object.function]]
    name = "set_selected_channels"
    ignore = true
    [[object.function]]
    name = "set_selected_layers"
    ignore = true
    [[object.function]]
    name = "set_selected_paths"
    ignore = true

[[object]]
name = "Gimp.*"
status = "generate"
    [[object.function]]
    name = "color_list_names"
    ignore = true
    [[object.function]]
    name = "color_parse_css_substring"
    ignore = true
    [[object.function]]
    name = "color_parse_hex_substring"
    ignore = true
    [[object.function]]
    name = "color_parse_name_substring"
    ignore = true
    [[object.function]]
    name = "edit_copy"
    ignore = true
    [[object.function]]
    name = "edit_cut"
    ignore = true
    [[object.function]]
    name = "edit_named_copy"
    ignore = true
    [[object.function]]
    name = "edit_named_cut"
    ignore = true
    [[object.function]]
    name = "enum_get_value"
    ignore = true
    [[object.function]]
    name = "flags_get_first_value"
    ignore = true
    [[object.function]]
    name = "color_array_copy"
    ignore = true
    [[object.function]]
    name = "color_array_free"
    ignore = true
    [[object.function]]
    name = "color_array_get_length"
    ignore = true
    [[object.function]]
    name = "core_object_array_get_length"
    ignore = true
    [[object.function]]
    name = "cairo_surface_create_buffer"
    ignore = true
    [[object.function]]
    name = "cairo_surface_get_format"
    ignore = true
    [[object.function]]
    name = "color_is_out_of_gamut"
    ignore = true
    [[object.function]]
    name = "pixbuf_get_format"
    ignore = true
    [[object.function]]
    name = "cairo_checkerboard_create"
    ignore = true

[[object]]
name = "Gimp.PlugIn"
status = "generate"
    [[object.property]]
    name = "read-channel"
    ignore = true
    [[object.property]]
    name = "write-channel"
    ignore = true

[[object]]
name = "Gimp.ValueArray"
status = "generate"
    [[object.function]]
    name = "new_from_values"
    ignore = true

[[object]]
name = "Gimp.Layer"
status = "generate"
    [[object.function]]
    name = "new_from_surface"
    ignore = true
